### ISSUE TITLE
Use with Swift 4

### ISSUE THREAD

**Issue by n1schal** [awkward/Tatsi#20]
I tried adding the source files manually, and I'm stuck as to what I should do for the project to build at 

`guard let image = (info[UIImagePickerController.InfoKey.editedImage] as? UIImage) ?? (info[UIImagePickerController.InfoKey.originalImage] as? UIImage) else {
            return
        }`

in the didFinishPickingMediaWithInfo delegate method in AssetsGridViewController

**Comment by n1schal** [comment]
Changed the whole thing to 

```
func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : Any]) {
        guard let image = (info[UIImagePickerControllerOriginalImage] as? UIImage) ?? (info[UIImagePickerControllerEditedImage] as? UIImage) else {
            return
        }
        self.createAsset(from: image) { [weak self] (asset, error) in
            if let asset = asset {
                self?.addAsset(asset)
                self?.selectAsset(asset)
            } else if let error = error {
                print("Error saving photo \(error)")
            } else {
                self?.startFetchingAssets()
            }
        }
        picker.dismiss(animated: true, completion: nil)
    }
```

And it built.

**Comment by n1schal** [comment]
Can't seem to get the "Done" button working though.

**Comment by renssies** [comment]
That's normal, Swift 4.2 introduced a "key" type for lots of these kinds of dictionary types. While Swift 1-4 still used the string type from Objective-C.
