### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by srbalan** [awkward/Tatsi#21]
I run the example project. Everything went well, however, it seems there's a memory leak every time I present the picker controller. Could you check it? I attached video recording of the Xcode Instrument.

[Tatsi-Possilbe-Memory-Leak.mov.zip](https://github.com/awkward/Tatsi/files/3111446/Tatsi-Possilbe-Memory-Leak.mov.zip)

**Comment by renssies** [comment]
I've checked for memory leaks before and I believe to remember that this memory leak resides somewhere in the Photos framework (like PHAssetLibrary, PHAsset or PHImageManager). But I will have another look at it next week.
