### ISSUE TITLE
Last selected album or library

### ISSUE THREAD

**Issue by ravivlb** [awkward/Tatsi#41]
How to keep last selected album or library

**Comment by renssies** [comment]
Good question! It is possible to open the picker onto a certain album with the following code:
```Swift
let collection = self.lastCollection // This is a PHAssetCollection which you retreive from PhotosKit
var config = TatsiConfig.default
config.firstView = .album(collection)
let pickerViewController = TatsiPickerViewController(config: config)
pickerViewController.pickerDelegate = self
self.present(pickerViewController, animated: true, completion: nil)
```

However, now that you ask this question, Tasti doesn't return the current album the user has selected. 

I'm working on adding a delegate method that communicates which album the user has selected so you can retain that information.

**Comment by renssies** [comment]
I have just pushed the change to the repository and Cocoapods repo. Version 1.2 should contain the delegate method that gives you the user's selected album. 

I've also added the retaining of the last selected album to the example.
