### ISSUE TITLE
pod not available ?

### ISSUE THREAD

**Issue by poonamdhomane** [awkward/Tatsi#8]

**Comment by renssies** [comment]
For some reason, the latest Podspec does not appear to be on Cocoapods.org. I'm going to investigate that. 

You can however use Tatsi right now by adding the following to your podfile:
```Gemfile
pod 'Tatsi',  :git => 'git@github.com:awkward/Tatsi.git', :tag => '1.1'
```

**Comment by renssies** [comment]
Tatsi 1.1 should now be available using cocoapods.org: https://cocoapods.org/pods/Tatsi

**Comment by poonamdhomane** [comment]
Thanks a lot
