### ISSUE TITLE
Images and Videos don't show up.

### ISSUE THREAD

**Issue by sonuvr4u** [awkward/Tatsi#9]
On the simulator and device,
  `config.supportedMediaTypes = [.image] or    config.supportedMediaTypes = [.video] `
The above configuartion doesn't show photos or videos.
But  `config.supportedMediaTypes = [.image, .video]` shows up both image and video as expected.

Edit: 
Never mind.
Fixed it by changing to `guard self.supportedMediaTypes.contains(.image) || self.supportedMediaTypes.contains(.video) && self.supportedMediaSubTypes == nil else {
            return nil
        }
` in TatsiConfig.swift - line 112. Changed && to ||

**Comment by renssies** [comment]
Thanks, I will apply this fix in the master branch. 

You could also make a PR and claim the credit if you want :)

**Comment by renssies** [comment]
Fixed it in master and updated Cocoapods. Thanks for notifying me of this issue :)

**Comment by sonuvr4u** [comment]
Noticed this just now. Couldn't keep track due to my day job. Btw, thanks for the wonderful library!
